// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEW_Test_240321.model;

namespace SEW_Test_240321.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("SEW_Test_240321.model.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ARTIST_ID");

                    b.Property<string>("Epoche")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("EPOCHE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LAST_NAME");

                    b.HasKey("Id");

                    b.ToTable("ARTISTS");
                });

            modelBuilder.Entity("SEW_Test_240321.model.WorkOfArt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ARTWORK_ID");

                    b.Property<int?>("ARTIST")
                        .HasColumnType("int");

                    b.Property<int>("AestimatedValue")
                        .HasColumnType("INT")
                        .HasColumnName("AESTIMATED_VALUE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("ARTIST");

                    b.ToTable("WORK_OF_ART_BT");
                });

            modelBuilder.Entity("SEW_Test_240321.model.Painting", b =>
                {
                    b.HasBaseType("SEW_Test_240321.model.WorkOfArt");

                    b.Property<int>("Height")
                        .HasColumnType("INT")
                        .HasColumnName("HEIGHT");

                    b.Property<int>("Width")
                        .HasColumnType("INT")
                        .HasColumnName("WIDTH");

                    b.ToTable("PAINTING");
                });

            modelBuilder.Entity("SEW_Test_240321.model.Sculpture", b =>
                {
                    b.HasBaseType("SEW_Test_240321.model.WorkOfArt");

                    b.Property<int>("Weight")
                        .HasColumnType("INT")
                        .HasColumnName("WEIGHT");

                    b.ToTable("SCULPTURE");
                });

            modelBuilder.Entity("SEW_Test_240321.model.Setup", b =>
                {
                    b.HasBaseType("SEW_Test_240321.model.WorkOfArt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DESCRIPTION");

                    b.ToTable("SETUP");
                });

            modelBuilder.Entity("SEW_Test_240321.model.WorkOfArt", b =>
                {
                    b.HasOne("SEW_Test_240321.model.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ARTIST");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SEW_Test_240321.model.Painting", b =>
                {
                    b.HasOne("SEW_Test_240321.model.WorkOfArt", null)
                        .WithOne()
                        .HasForeignKey("SEW_Test_240321.model.Painting", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SEW_Test_240321.model.Sculpture", b =>
                {
                    b.HasOne("SEW_Test_240321.model.WorkOfArt", null)
                        .WithOne()
                        .HasForeignKey("SEW_Test_240321.model.Sculpture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SEW_Test_240321.model.Setup", b =>
                {
                    b.HasOne("SEW_Test_240321.model.WorkOfArt", null)
                        .WithOne()
                        .HasForeignKey("SEW_Test_240321.model.Setup", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
